targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true

      source_gen:combining_builder: 
        options:
          build_extensions:
            '^lib/data/models/{{subfolder}}/{{}}.dart': 'lib/generated/{{subfolder}}/{{}}.g.dart'


      freezed:
        options:
          build_extensions:
            '^lib/data/models/{{subfolder}}/{{}}.dart': 'lib/generated/{{subfolder}}/{{}}.freezed.dart'

      flutter_gen_runner:
        options:
          output: lib/generated/assets/